version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Run test coverage
          command: npm run test:coverage
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: coverage
  
  deploy:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Deploy to production
          command: echo "Em um cenário real, aqui teríamos os comandos para deploy"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main